name: PECUZAL Python

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        py:
          - "3.7"
          - "3.8"
          - "3.9"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python for testing ${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip
    - name: Install tox
      run: pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
